//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPV_Loader
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsasaraActivationType
    {
        public int Id { get; set; }
        public string ActivationType { get; set; }
        public string DataTemplateName { get; set; }
        public string DataTemplatePath { get; set; }
        public string PptTemplatePath { get; set; }
    }
}
