//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPV_Loader
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsasaraJob
    {
        public string OrderOsLink { get; set; }
        public Nullable<int> JobNumber { get; set; }
        public Nullable<int> SalesOrder { get; set; }
        public Nullable<int> BuildQty { get; set; }
        public Nullable<int> CustomerAccountCode { get; set; }
        public string PartNumber { get; set; }
        public string OCR { get; set; }
        public string Campaign_ID { get; set; }
        public string Project_ID { get; set; }
        public string MMYY { get; set; }
        public string Integrator_Share { get; set; }
        public string Printer_Share { get; set; }
        public string Identifier { get; set; }
        public string Line_Description { get; set; }
        public string Country { get; set; }
        public string Integrator_Product_ID { get; set; }
        public string Quantity { get; set; }
        public string In_DC_Date { get; set; }
        public string Production_UPC { get; set; }
        public string Form_Factor { get; set; }
        public string Denomination { get; set; }
        public string Partner_Encoding_Type { get; set; }
        public string Internal_Activation { get; set; }
        public string Production_Run_group { get; set; }
        public string Is_UPC_On_Card { get; set; }
        public string Is_Reprint { get; set; }
        public Nullable<int> Google_FAI_Quantity { get; set; }
        public Nullable<int> Integrator_FAI_Quantity { get; set; }
        public Nullable<int> Test_Quantity_Production_Data_Proof { get; set; }
        public Nullable<int> Test_Quantity_Sandbox_Dev { get; set; }
        public string Ship_To_Location_Text { get; set; }
        public string Ship_To_Location_Contact { get; set; }
        public string Ship_To_Location_1_Test_Cards_Text { get; set; }
        public string Ship_To_Location_1_Test_Cards_Contact { get; set; }
        public string Ship_To_Location_2_Test_Cards_Text { get; set; }
        public string Ship_To_Location_2_Test_Cards_Contact { get; set; }
        public Nullable<int> Cards_Per_Pack { get; set; }
        public Nullable<int> Packs_Per_Carton { get; set; }
        public Nullable<int> Cards_Per_Carton { get; set; }
        public string Pack_EAN { get; set; }
        public string Pallet_EAN { get; set; }
        public string Case_EAN { get; set; }
        public string Spec_Guide_Version { get; set; }
        public string Logistics_Guide_Version { get; set; }
        public string NAN___Shipping_PO___Product_Packing_Label { get; set; }
        public string BHN_Brand_Code___BHN_1st_Case_Quantity___PID_Number { get; set; }
        public string BHN_Pack_Description___Packing_UPC { get; set; }
        public string Packaging___Encoding_Identifier { get; set; }
        public string Label_Spec { get; set; }
        public string Outer_Box_Caption { get; set; }
        public string Is_Card_Import_File_Required { get; set; }
        public string Is_Send_First_Box_To_BHN { get; set; }
    }
}
