//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPV_Loader
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsasaraWorkInstruction
    {
        public string Campaign_ID__rName { get; set; }
        public string Integrator_Project_ID__c { get; set; }
        public string Printer_Project_ID__c { get; set; }
        public string MMYY__c { get; set; }
        public string Integrator_SHARE__c { get; set; }
        public string Printer_SHARE__c { get; set; }
        public string Identifier__c { get; set; }
        public string Line_Description__c { get; set; }
        public string Country__c { get; set; }
        public string Integrator_Product_ID__c { get; set; }
        public string In_DC_Quantity__c { get; set; }
        public string In_DC_Date__c { get; set; }
        public string Production_UPC__c { get; set; }
        public string Form_Factor__c { get; set; }
        public string Denomination__c { get; set; }
        public string Partner_Encoding_Type__c { get; set; }
        public string Internal_Activation__c { get; set; }
        public string Production_Run_Group__c { get; set; }
        public string IsUpcOnCard__c { get; set; }
        public string IsReprint__c { get; set; }
        public Nullable<int> Google_FAI_Quantity__c { get; set; }
        public Nullable<int> Integrator_FAI_Quantity__c { get; set; }
        public Nullable<int> Test_Quantity_Prod_Data_Proof__c { get; set; }
        public Nullable<int> Test_Quantity_Sandbox_Dev__c { get; set; }
        public Nullable<int> Production_Quantity__c { get; set; }
        public Nullable<int> Google_Data_Production_Quantity__c { get; set; }
        public string Ship_to_Location_Text__c { get; set; }
        public string Ship_to_Location_Contact__c { get; set; }
        public string Ship_to_Location_1_Test_Cards_Text__c { get; set; }
        public string Ship_to_Location_1_Test_Cards_Contact__c { get; set; }
        public string Ship_to_Location_2_Test_Cards_Text__c { get; set; }
        public string Ship_to_Location_2_Test_Cards_Contact__c { get; set; }
        public Nullable<int> Cards_per_Pack__c { get; set; }
        public Nullable<int> Packs_per_Carton__c { get; set; }
        public Nullable<int> Cards_per_Carton__c { get; set; }
        public string Pack_EAN__c { get; set; }
        public string Pallet_EAN__c { get; set; }
        public string Case_EAN__c { get; set; }
        public string Spec_Guide_Version__c { get; set; }
        public string Logistics_Guide_Version__c { get; set; }
        public string NAN_Code__c_Shipping_PO_c_Product_Packing_Label_c { get; set; }
        public string BHN_Brand_Code_c_BHN_1st_Case_Quantity_c_PID_Number_c { get; set; }
        public string BHN_Pack_Description_c_Packing_UPC_c { get; set; }
        public string Packaging__c_Encoding_Identifier__c { get; set; }
        public string Label_Spec__c { get; set; }
        public string Outerbox_Caption__c { get; set; }
        public string IsCardImportFileRequired__c { get; set; }
        public string IsSendFirstBoxToBHN__c { get; set; }
        public int ID { get; set; }
    }
}
