//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPV_Loader
{
    using System;
    using System.Collections.Generic;
    
    public partial class AthenaJob
    {
        public int Id { get; set; }
        public string JobNumber { get; set; }
        public string DueDate { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string PurchaseOrderLine { get; set; }
        public string SalesOrderNumber { get; set; }
        public string CustomerAccountCode { get; set; }
        public Nullable<int> JobQuantity { get; set; }
        public string AscmOrderId { get; set; }
        public string EndCustomer { get; set; }
        public string ActivationSystem { get; set; }
        public string ProductType { get; set; }
        public string ErpMaterialCode { get; set; }
        public string IntegratorPartID { get; set; }
        public string IntegratorID { get; set; }
        public string ActivationType { get; set; }
        public string PartNumberSku { get; set; }
        public string RetailBarcode { get; set; }
        public string RetailBarcodeType { get; set; }
        public string Channel { get; set; }
    }
}
