//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPV_Loader
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportAthena
    {
        public int Id { get; set; }
        public string JobId { get; set; }
        public string OrderId { get; set; }
        public string PurchaseOrderNumber { get; set; }
        public string PurchaseOrderLine { get; set; }
        public string CustomerAccountCode { get; set; }
        public string JobQty { get; set; }
        public string ASCMOrderID { get; set; }
        public string EndCustomer { get; set; }
        public string ActivationSystem { get; set; }
        public string ProductType { get; set; }
        public string ErpMaterialCode { get; set; }
        public string FAIStart { get; set; }
        public string FAIEnd { get; set; }
        public string ContractTypeLVId { get; set; }
        public string PartNumberSku { get; set; }
        public string JobComments { get; set; }
        public string JobTypeLVId { get; set; }
        public string SpecificationLVId { get; set; }
        public string UPC { get; set; }
        public string ArtworkPartNumber { get; set; }
        public string PackQty { get; set; }
        public string BoxQty { get; set; }
        public string PalletQty { get; set; }
        public string Description { get; set; }
        public string IncommRetailer { get; set; }
        public string IncommProductDescription { get; set; }
        public string Denomination { get; set; }
        public string DenominationCurrency { get; set; }
        public string AlternativePartNumber { get; set; }
        public string PackagingGTIN { get; set; }
        public string BHNPONumber { get; set; }
        public string MSRequestNumber1 { get; set; }
        public string BOMComment1 { get; set; }
        public string PKPN1 { get; set; }
        public string MSRequestNumber2 { get; set; }
        public string BOMComment2 { get; set; }
        public string PKPN2 { get; set; }
        public string MSRequestNumber3 { get; set; }
        public string BOMComment3 { get; set; }
        public string PKPN3 { get; set; }
        public string MSRequestNumber4 { get; set; }
        public string BOMComment4 { get; set; }
        public string PKPN4 { get; set; }
        public string MSRequestNumber5 { get; set; }
        public string BOMComment5 { get; set; }
        public string PKPN5 { get; set; }
    }
}
