//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPV_Loader
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportAsasara
    {
        public int Id { get; set; }
        public string orderID { get; set; }
        public string jobID { get; set; }
        public string jobQty { get; set; }
        public string integratorName { get; set; }
        public string activationType { get; set; }
        public string regionID { get; set; }
        public string pptQty { get; set; }
        public string denomination { get; set; }
        public string currency { get; set; }
        public string retailBarcode { get; set; }
        public string customerJobNumber { get; set; }
        public string integratorID { get; set; }
        public string productDescription { get; set; }
        public string maskID { get; set; }
        public string dummyRecords { get; set; }
        public string dummyRecordsCount { get; set; }
        public string dummyRecordsEvery { get; set; }
        public string packQty { get; set; }
        public string caseQty { get; set; }
        public string palletQty { get; set; }
        public string expiryDate { get; set; }
        public string whiteCardTestQty { get; set; }
        public string retailBarcodeType { get; set; }
        public string barcodeStyleType { get; set; }
        public string alternativePartNumber { get; set; }
        public string country { get; set; }
        public string eanBundle { get; set; }
        public string eanBox { get; set; }
        public string DODHumanFontTypeID { get; set; }
        public string partnerTextBox { get; set; }
        public string partnerCode { get; set; }
        public string brand { get; set; }
        public string VASBoxDescription { get; set; }
        public string palletTypeID { get; set; }
        public string comments { get; set; }
        public string recipientAddress1 { get; set; }
        public string recipientAddress2 { get; set; }
        public string recipientAddress3 { get; set; }
        public string recipientAddress4 { get; set; }
        public string recipientAddress5 { get; set; }
        public string recipientAddress6 { get; set; }
        public string codeFormat { get; set; }
        public string vasType { get; set; }
        public string FAIQty { get; set; }
        public string OCR { get; set; }
        public string VASPackDescription { get; set; }
        public string labelStyle { get; set; }
        public string activationMode { get; set; }
        public string pinFile { get; set; }
        public string WCTPinFile { get; set; }
        public string eanPallet { get; set; }
        public string BHNPONumber { get; set; }
    }
}
