//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPV_Loader
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Nullable<int> JobNumber { get; set; }
        public Nullable<int> SalesOrder { get; set; }
        public Nullable<int> BuildQty { get; set; }
        public Nullable<int> CustomerAccountCode { get; set; }
        public string PartNumber { get; set; }
        public string OCR { get; set; }
        public string OrderOsLink { get; set; }
        public int ID { get; set; }
    }
}
