//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPV_Loader
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SpvLoaderEntities : DbContext
    {
        public SpvLoaderEntities()
            : base("name=SpvLoaderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AsasaraActivationType> AsasaraActivationTypes { get; set; }
        public virtual DbSet<AsasaraJob> AsasaraJobs { get; set; }
        public virtual DbSet<AsasaraRegionLookup> AsasaraRegionLookups { get; set; }
        public virtual DbSet<AsasaraWorkInstruction> AsasaraWorkInstructions { get; set; }
        public virtual DbSet<AthenaJob> AthenaJobs { get; set; }
        public virtual DbSet<BHNWorkInstruction> BHNWorkInstructions { get; set; }
        public virtual DbSet<Dach> Daches { get; set; }
        public virtual DbSet<ExportAsasara> ExportAsasaras { get; set; }
        public virtual DbSet<ExportAthena> ExportAthenas { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Asasara_Order_WorkInstructions> Asasara_Order_WorkInstructions { get; set; }
    }
}
